name: GitHub-Profile-Summary-Cards

on:
  schedule: # Esegue l'aggiornamento automatico ogni 24 ore
    - cron: "0 0 * * *"
  workflow_dispatch: # Ti permette di avviarlo manualmente quando vuoi

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARDS_TOKEN }}
        with:
          USERNAME: ChiaraCapaccioni
          # Ho messo il tuo user personale così legge i tuoi veri dati!
